[Theme]
Current=astronaut

[Autologin]
# Uncomment to enable autologin (skip password on first boot)
# User=iubeha
# Session=hyprland

[General]
# Use Wayland compositor for SDDM itself
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell

[Wayland]
CompositorCommand=kwin_wayland --drm --no-lockscreen --no-global-shortcuts --locale1
